on: [push, pull_request]

jobs:
  linux:
    strategy:
      fail-fast: false
      matrix:
        profile: [Clang-shared-debug, Clang-static-release, Gcc-shared-debug]
        recipe: [5.15.1, 5.14.1, 5.13.2, 5.12.9]
    runs-on:  ubuntu-20.04
    steps:
      - name: Install system packages
        run: |
          sudo apt-get update
          sudo apt-get -qq install -y --no-install-recommends python3-pip python3-setuptools graphviz clang-format-10 clang-10 clang-tidy-10 ninja-build m4 clang
      - name: install conan
        run: pip3 install conan
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: Knitschi/CIBuildConfigurations
          path: profiles
      - name: run
        env:
          CONAN_SYSREQUIRES_MODE: enabled
        run: |
          ~/.local/bin/conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan 
          ~/.local/bin/conan install Sources/QtTestConsumer/conanfile_Qt${{ matrix.recipe }}.txt -pr profiles/ConanProfile-${{ matrix.profile }} --build missing
  
  Windows:
    strategy:
      fail-fast: false
      matrix:
        profile: [VS2019-shared-debug, VS2019-static-release]
        recipe: [5.15.1, 5.14.1, 5.13.2, 5.12.9]
    runs-on:  windows-latest
    steps:
      - name: install
        run: pip3 install conan
      - uses: actions/checkout@v2
      - uses: actions/checkout@v2
        with:
          repository: Knitschi/CIBuildConfigurations
          path: profiles
      - name: run
        run: |
          conan remote add bincrafters https://api.bintray.com/conan/bincrafters/public-conan 
          conan install Sources/QtTestConsumer/conanfile_Qt${{ matrix.recipe }}.txt -pr profiles/ConanProfile-${{ matrix.profile }} --build missing
